### ISSUE TITLE
Is it possible for custom items in itemsadder to be added to jobs payout?

### ISSUE THREAD

**Issue by Darcon31** [mrfdev/Jobs#5]
Hello, Is it possible for custom items in itemsadder to be added to jobs payout? so if I have an itemsadder item called cheese, I can make it so cooking cheese pays my chef job??

**Comment by mrfloris** [comment]
Wrong github :) zrips' github for jobs is here: 
https://github.com/Zrips/Jobs/ 

I also don't know the answer to your question, no experience with itemsadder like that.
